# Use Node.js base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json .

RUN apk add --no-cache python3 py3-pip make g++
# RUN python3 -v
# Install dependencies
RUN npm install 

# Copy the rest of the project files
COPY . .

# Expose the React development server port
EXPOSE 3000

# Start the React development server
CMD ["npm","run", "start"]
