# Use Node.js base image
FROM python:3.11.3-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY requirements.txt .

RUN pip install -r requirements.txt
# RUN python3 -v
# Install dependencies


# Copy the rest of the project files
COPY . .

# Expose the React development server port
EXPOSE 5001

# Start the React development server
CMD ["python3", "app.py"] 
