apiVersion: v1
kind: Service
metadata:
  name: vasthavik-frontend
  labels:
    app: vasthavik
    component: frontend
  annotations:
    # AWS NLB for external access
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: vasthavik
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
